DROP TRIGGER IF EXISTS set_version ON message;
DROP SEQUENCE IF EXISTS version;
DROP TABLE IF EXISTS message;
DROP TABLE IF EXISTS replicache_client;
DROP TABLE IF EXISTS document_message;
DROP TABLE IF EXISTS template_message;
DROP TABLE IF EXISTS document;
DROP TABLE IF EXISTS template;
DROP TABLE IF EXISTS team_member;
DROP TABLE IF EXISTS team;
DROP TABLE IF EXISTS organization;
DROP TABLE IF EXISTS profile;

-- Stores user profile information
CREATE TABLE profile (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  user_id UUID NOT NULL UNIQUE,
  avatar UUID
);

-- Stores organization data    
CREATE TABLE organization (  
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author_id BIGINT NOT NULL REFERENCES profile,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  hash TEXT NOT NULL DEFAULT MD5(random()::text),
  avatar UUID
);

-- Stores organization team    
CREATE TABLE team (  
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES organization,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  color TEXT NOT NULL DEFAULT '#ff0000',
  avatar UUID
);

-- Stores organization team members    
CREATE TABLE team_member (  
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id BIGINT NOT NULL REFERENCES profile,
  team_id BIGINT NOT NULL REFERENCES team,
  role TEXT NOT NULL,
  UNIQUE (profile_id, team_id)
);

-- Stores workflow templates    
CREATE TABLE template (  
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES organization,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  avatar UUID
);

-- Stores workflow documents    
CREATE TABLE document (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES organization,
  template_id BIGINT NOT NULL REFERENCES template,
  template_data JSON NOT NULL,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  avatar UUID
);

-- Stores template messages    
CREATE TABLE template_message (      
    id VARCHAR(21) PRIMARY KEY NOT NULL,      
    template_id BIGINT NOT NULL REFERENCES template,
    data JSON NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Stores template messages    
CREATE TABLE document_message (      
    id VARCHAR(21) PRIMARY KEY NOT NULL,      
    document_id BIGINT NOT NULL REFERENCES document,
    data JSON NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Stores last mutation ID for each Replicache client    
CREATE TABLE replicache_client (
    id VARCHAR(36) PRIMARY KEY NOT NULL,      
    last_mutation_id BIGINT NOT NULL
);

-- Sync between users and profile tables
CREATE OR REPLACE FUNCTION signup_copy_to_profile_table()
RETURNS TRIGGER AS $$
  BEGIN
    INSERT INTO public.profile (user_id, name)
    VALUES(new.id, new.email);
  
    RETURN NEW;
  END;
$$
LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS signup_copy on auth.users;
CREATE TRIGGER signup_copy
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE PROCEDURE signup_copy_to_profile_table();

-- Create default organization for new profile
CREATE OR REPLACE FUNCTION create_default_organization()
RETURNS TRIGGER AS $$
  BEGIN
    INSERT INTO public.organization (author_id, name, description)
    VALUES(new.id, new.name, '');
  
    RETURN NEW;
  END;
$$
LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS default_organization on public.profile;
CREATE TRIGGER default_organization
AFTER INSERT ON public.profile
FOR EACH ROW EXECUTE PROCEDURE create_default_organization();

-- Update updated_at time
create extension if not exists moddatetime schema extensions;

DROP TRIGGER IF EXISTS template_message_updated_at on public.template_message;
create trigger template_message_updated_at 
before update on public.template_message 
for each row execute procedure moddatetime (updated_at);

DROP TRIGGER IF EXISTS document_message_updated_at on public.document_message;
create trigger document_message_updated_at 
before update on public.document_message 
for each row execute procedure moddatetime (updated_at);
